# Generated by Django 3.0.4 on 2020-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('emailId', models.EmailField(max_length=30)),
                ('contactNo', models.CharField(max_length=10)),
                ('streetAddress', models.TextField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.PositiveIntegerField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('ProfSkill', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=30)),
                ('workExp', models.CharField(max_length=50)),
                ('workStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
