# Generated by Django 3.0.4 on 2020-03-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUNNY', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='ProfSkill',
            new_name='skillSet',
        ),
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='zipcode',
            new_name='zipCode',
        ),
    ]
